branches:
  only:
  - trunk
  - stable
language: java
env:
  global:
jdk:
- oraclejdk8
install:
- mvn clean install -Dgpg.skip=true -DskipTests=true -P !build-extras -B -V
before_script: 
script: mvn test -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"
after_failure:
- cat com.github.lafa.logfast/target/surefire-reports/*.txt
- cat com.github.lafa.logfast/core/target/surefire-reports/*.txt
